Add HW from projects list, merge ZMK
zephyrproject-rtos/awesome-zephyr-rtos pull request #1
Opened 2024-06-04 15:44 UTC by mgielda

2024-07-02 08:50 UTC, kartben requested changes

2024-07-02 08:50 UTC, kartben commented on README.md
> +* [ChromeOS Embedded Controller (EC)](https://chromium.googlesource.com/chromiumos/platform/ec/+/refs/heads/main/docs/zephyr/README.md#Shared-Code)
this "typo" is causing the list to render ever so slightly odd:

```suggestion
- [ChromeOS Embedded Controller (EC)](https://chromium.googlesource.com/chromiumos/platform/ec/+/refs/heads/main/docs/zephyr/README.md#Shared-Code)
```

2024-07-03 14:36 UTC, mgielda commented
If that is the only comment, please merge :)

2024-07-11 16:32 UTC, kartben approved these changes

2024-07-18 12:31 UTC, merged